spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}Job
      chunk-size : 100
      thread-pool : 1
      enabled: false

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      #enabled: true
      force: true