spring:
  config:
    import:
      - quartz-config.yml

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
      username: sa
      password:
      driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      platform: test