DROP TABLE IF EXISTS MEMBER;
DROP TABLE IF EXISTS EVEN_MEMBER_ID;

CREATE TABLE MEMBER COMMENT '회원' (
    MEMBER_ID      NUMBER(10)     NOT NULL    COMMENT '회원ID'
    , NAME        VARCHAR(100)                COMMENT '회원명'
    , PRIMARY KEY (MEMBER_ID)
    );


CREATE TABLE EVEN_MEMBER_ID COMMENT '짝수 멤버아이디' (
    MEMBER_ID      NUMBER(10)     NOT NULL    COMMENT '회원ID',
    FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBER (MEMBER_ID)
    );